import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import '../public/css/bootstrap.min.css';
import '../public/css/plugins.css';
import '../public/css/swiper.css';
import '../public/css/style.css';
import '../public/css/coloring.css';
import '../public/css/colors/scheme-01.css';
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "@/components/header";
import Footer from "@/components/Footer";
import Providers from "@/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Yatra | Next Gen Tourism",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico", // Path to your favicon
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <head>
                {/* Other head elements */}
            </head>
            <body style={{ backgroundColor: "#c9c9c9" }}>
                <SessionProvider session={session}>
                    <div id="wrapper">
                        <Navbar />
                        <Providers>
                            {children}
                        </Providers>
                        <Footer />
                    </div>
                </SessionProvider>
                <Script src="./js/plugins.js"></Script>
                <Script src="./js/designesia.js"></Script>
                <Script src="./js/swiper.js"></Script>
                <Script src="./js/custom-marquee.js"></Script>
                <Script src="./js/custom-swiper-2.js"></Script>
                <Script src="https://embed.elephant.ai/static/js/chatbot.js" id="89cb8d4d-4eeb-4a22-b2cc-d42466840827" />
            </body>
        </html>
    );
}
